BLUEPRINT_GSHEET_ID: "1fNi9vGrXlAXdqHzyOFrWHqIT1ZKY_QbBd6qEnBg_FGI"
MODULE_GSHEET_ID: "1D85blrWeCs9gMpeihZ6s8_KfY1tOUEmK2sgl-5BL4Gs"
SCRAP_GSHEET_ID: "1n1s5u2aypE8Uh5w3BPV5KAoz-tKmUubchAvPJiT5Vxs"

# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a17a5817d23bde1241193bf16482b4a846de0c1c1d01aa401039ef1b325672775636aa8009c7ce53087ea24ff3ab8d21d39a6d4047b7804409439b6af1d74c9d

test:
  secret_key_base: 2e1e98f6e60818b94d2016393b7543b2e6b6be0b546bd279e20be9a189953409d636b8c5f8cb113a6dd228658399fc6916afce1fb209b6128b0e4d6f8145a62c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
